trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: CmdLine@2
  displayName: Docker Build
  inputs:
    script: 'docker build  -t teste-$(Build.BuildId) .'
    workingDirectory: './app'
    
- task: CmdLine@2
  displayName: Docker Login
  inputs:
    script: 'docker login --username edvl --password $(DOCKER_PASS)'

- task: CmdLine@2
  displayName: Docker push
  inputs:
    script: 'docker push edvl/test:teste-$(Build.BuildId)'