trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 'ah'
    command: build
    Dockerfile: app/Dockerfile
    tags: dtest-$(Build.BuildId)
    
- task: CmdLine@2
  displayName: Docker Login
  inputs:
    script: 'docker login --username edvl --password $(DOCKER_PASS)'

- task: CmdLine@2
  displayName: Docker push
  inputs:
    script: 'docker push edvl/test:ah:dtest-$(Build.BuildId)'